version: '3'
services: 
    ########################
    # Setup backend Server Container
    ########################
    backend:
        build: ./backend
        expose: 
            - ${APP_SERVER_PORT}
        environment: 
            API_HOST: ${API_HOST}
            APP_SERVER_PORT: ${APP_SERVER_PORT}             
        ports: 
            - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
        volumes: 
            - ./backend:/usr/src/app
        command: npm run start

            #######################
            # setup frontend Client Container
            ########################
    
    frontend:
        build: ./frontend
        environment: 
            - REACT_APP_PORT=${REACT_APP_PORT}
        expose: 
            - ${REACT_APP_PORT}                    
        ports: 
            - ${REACT_APP_PORT}:${REACT_APP_PORT}                           
        links:
            - backend                
        command: npm run start